// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDirectoryContents(arg1:string):Promise<Array<main.FileSystemItem>>;

export function GetDrives():Promise<Array<main.FileSystemItem>>;

export function GetFileSystemItem(arg1:string):Promise<main.FileSystemItem>;

export function GetRootDirectories():Promise<Array<main.FileSystemItem>>;

export function Greet(arg1:string):Promise<string>;
